namespace DataObjects
{
    public enum EdEvent
    {
        AddButtonClicked,
        BackButtonClicked,
        DeleteButtonClicked,
        SaveButtonClicked,
        DuplicateButtonClicked,
        DuplicateFourButtonClicked,
        CancelButtonClicked,
        AddTreesButtonClicked,
        InstanceChanged,
        ManagementUnitChanged,
        AppConSelectionChanged,
        PropertyLoaded,
        NoValidData,
        SaveAllowed,
        DeleteAllowed,
        NewRecord,
        AcquisitionUnitLoaded,
        AcquisitionUnitChanged,
        SafetyPageLoaded,
        ManagementUnitLoaded,
        PaneButtonClicked,
        PageChanged,
        RefreshParent,
        ShowWait,
        HideWait,
        WaitDisplayed,
        ApplicationChanged
    }
}