using System;

namespace DataObjects.DTOS.ManagementPlans.SearchScreens
{
    public class WoodlandconditionsubsectionDTO
    {
        public int ID { get; set; }
        public int FeatureMonitoringID { get; set; }
        public bool WholeSite { get; set; }
        public int? KeyFeatureID { get; set; }
        public int? StratumID { get; set; }
        public string StratumDescription { get; set; }
        public bool? OverallInterventionDesirable { get; set; }
        public bool? OverallInterventionAchievable { get; set; }
        public string OverallConclusionsAndRecommendations { get; set; }
        public int? TotalTreeCanopyCoverPercentCurrent { get; set; }
        public int? TotalTreeCanopyCoverPercentMin { get; set; }
        public int? TotalTreeCanopyCoverPercentMax { get; set; }
        public int? OpenSpaceSemiNaturalHabitatPercentCurrent { get; set; }
        public int? OpenSpaceSemiNaturalHabitatPercentMin { get; set; }
        public int? OpenSpaceSemiNaturalHabitatPercentMax { get; set; }
        public int? OpenSpaceRidesPercentCurrent { get; set; }
        public int? OpenSpaceRidesPercentMin { get; set; }
        public int? OpenSpaceRidesPercentMax { get; set; }
        public int? OpenSpaceTemporaryPercentCurrent { get; set; }
        public int? OpenSpaceTemporaryPercentMin { get; set; }
        public int? OpenSpaceTemporaryPercentMax { get; set; }
        public int? OpenSpaceWaterFeaturesPercentCurrent { get; set; }
        public int? OpenSpaceWaterFeaturesPercentMin { get; set; }
        public int? OpenSpaceWaterFeaturesPercentMax { get; set; }
        public int? ShrubCoverPercentCurrent { get; set; }
        public int? ShrubCoverPercentMin { get; set; }
        public int? ShrubCoverPercentMax { get; set; }
        public bool? InterventionDesirable { get; set; }
        public bool? InterventionAchievable { get; set; }
        public string NotesAction { get; set; }
        public bool? TAOverall { get; set; }
        public bool? TAPlot1 { get; set; }
        public bool? TAPlot2 { get; set; }
        public bool? TAPlot3 { get; set; }
        public bool? TAPlot4 { get; set; }
        public bool? TAPlot5 { get; set; }
        public bool TAInterventionDesirable { get; set; }
        public bool TAInterventionAchievable { get; set; }
        public string TANotesActions { get; set; }
        public bool? TSOverall { get; set; }
        public bool? TSPlot1 { get; set; }
        public bool? TSPlot2 { get; set; }
        public bool? TSPlot3 { get; set; }
        public bool? TSPlot4 { get; set; }
        public bool? TSPlot5 { get; set; }
        public bool TSCanopyDominatedByOneOrTwoSPP { get; set; }
        public bool TSInterventionDesirable { get; set; }
        public bool TSInterventionAchievable { get; set; }
        public string TSNotesActions { get; set; }
        public bool? SSOverall { get; set; }
        public bool? SSPlot1 { get; set; }
        public bool? SSPlot2 { get; set; }
        public bool? SSPlot3 { get; set; }
        public bool? SSPlot4 { get; set; }
        public bool? SSPlot5 { get; set; }
        public bool SSShrubLayerDominatedByOneOrTwoSPP { get; set; }
        public bool SSInterventionDesirable { get; set; }
        public bool SSInterventionAchievable { get; set; }
        public string SSNotesActions { get; set; }
        public bool? LTROverall { get; set; }
        public bool? LTRPlot1 { get; set; }
        public bool? LTRPlot2 { get; set; }
        public bool? LTRPlot3 { get; set; }
        public bool? LTRPlot4 { get; set; }
        public bool? LTRPlot5 { get; set; }
        public bool LTRInterventionDesirable { get; set; }
        public bool LTRInterventionAchievable { get; set; }
        public string LTRNotesActions { get; set; }
        public bool? LSROverall { get; set; }
        public bool? LSRPlot1 { get; set; }
        public bool? LSRPlot2 { get; set; }
        public bool? LSRPlot3 { get; set; }
        public bool? LSRPlot4 { get; set; }
        public bool? LSRPlot5 { get; set; }
        public bool LSRInterventionDesirable { get; set; }
        public bool LSRInterventionAchievable { get; set; }
        public string LSRNotesActions { get; set; }
        public bool? RTSOverall { get; set; }
        public bool? RTSPlot1 { get; set; }
        public bool? RTSPlot2 { get; set; }
        public bool? RTSPlot3 { get; set; }
        public bool? RTSPlot4 { get; set; }
        public bool? RTSPlot5 { get; set; }
        public bool RTSInterventionDesirable { get; set; }
        public bool RTSInterventionAchievable { get; set; }
        public string RTSNotesActions { get; set; }
        public bool? RSSOverall { get; set; }
        public bool? RSSPlot1 { get; set; }
        public bool? RSSPlot2 { get; set; }
        public bool? RSSPlot3 { get; set; }
        public bool? RSSPlot4 { get; set; }
        public bool? RSSPlot5 { get; set; }
        public bool RSSInterventionDesirable { get; set; }
        public bool RSSInterventionAchievable { get; set; }
        public string RSSNotesActions { get; set; }
        public bool? FOverall { get; set; }
        public bool? FPlot1 { get; set; }
        public bool? FPlot2 { get; set; }
        public bool? FPlot3 { get; set; }
        public bool? FPlot4 { get; set; }
        public bool? FPlot5 { get; set; }
        public bool FInterventionDesirable { get; set; }
        public bool FInterventionAchievable { get; set; }
        public string FNotesActions { get; set; }
        public bool? DOverall { get; set; }
        public bool? DPlot1 { get; set; }
        public bool? DPlot2 { get; set; }
        public bool? DPlot3 { get; set; }
        public bool? DPlot4 { get; set; }
        public bool? DPlot5 { get; set; }
        public bool DInterventionDesirable { get; set; }
        public bool DInterventionAchievable { get; set; }
        public string DNotesActions { get; set; }
        public bool? ADOverall { get; set; }
        public bool? ADPlot1 { get; set; }
        public bool? ADPlot2 { get; set; }
        public bool? ADPlot3 { get; set; }
        public bool? ADPlot4 { get; set; }
        public bool? ADPlot5 { get; set; }
        public bool ADInterventionDesirable { get; set; }
        public bool ADInterventionAchievable { get; set; }
        public string ADNotesActions { get; set; }
        public bool? IOverall { get; set; }
        public bool? IPlot1 { get; set; }
        public bool? IPlot2 { get; set; }
        public bool? IPlot3 { get; set; }
        public bool? IPlot4 { get; set; }
        public bool? IPlot5 { get; set; }
        public bool IInterventionDesirable { get; set; }
        public bool IInterventionAchievable { get; set; }
        public string INotesActions { get; set; }
        public bool? THOverall { get; set; }
        public bool? THPlot1 { get; set; }
        public bool? THPlot2 { get; set; }
        public bool? THPlot3 { get; set; }
        public bool? THPlot4 { get; set; }
        public bool? THPlot5 { get; set; }
        public bool THInterventionDesirable { get; set; }
        public bool THInterventionAchievable { get; set; }
        public string THNotesActions { get; set; }
        public bool? HIOverall { get; set; }
        public bool? HIPlot1 { get; set; }
        public bool? HIPlot2 { get; set; }
        public bool? HIPlot3 { get; set; }
        public bool? HIPlot4 { get; set; }
        public bool? HIPlot5 { get; set; }
        public bool HIInterventionDesirable { get; set; }
        public bool HIInterventionAchievable { get; set; }
        public string HINotesActions { get; set; }
        public bool Deleted { get; set; }
        public bool IsProtected { get; set; }
        public bool IsHistorical { get; set; }
        public bool IsDefaultValue { get; set; }
        public DateTime LMDT { get; set; }
        public int LMUID { get; set; }
        public DateTime? CRDT { get; set; }
        public int? CRUID { get; set; }
        public DateTime? DLDT { get; set; }
        public int? DLUID { get; set; }
    }
}
